### ISSUE TITLE
the promise implementations do not provide Promise.when

### ISSUE THREAD

**Issue by bwl21** [clearwater-rb/bowser#16]
it seems that Bowser::ServiceWorker::Promise does not implement `Promise.when` as shown in http://opalrb.org/docs/guides/master/promises.html

Composing Promises

Promise.when can be used to wait for more than 1 promise to resolve (or reject). Lets assume we wanted to get 2 different users:
```ruby
first = get_json '/users/1.json'
second = get_json '/users/2.json'

Promise.when(first, second).then do |user1, user2|
  puts "got users: #{user1}, #{user2}"
end.fail do
  alert "Something bad happened"
end
```

**Comment by jgaskins** [comment]
`Promise.all` with an array should work.

```ruby
promises = user_ids.map { |id| get_json "/users/#{id}.json" }

Promise.all(promises)
  .then { |u1, u2| puts "got users: #{u1}" }
  .catch { |error| warn error }
```

If that _doesn't_ work, let's discuss it on #9 or #5 (whichever Promise implementation you're using) since those haven't been merged yet.

I used that API because it matches the [ES6 `Promise` spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all). I haven't really written it anywhere but a lot of stuff in Bowser is intended to be primarily a Ruby interface to browser APIs, so the [browser's JS API](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) is the interface I'm going for most of the time. This way, if you know the browser APIs, you probably know the Bowser APIs. If you don't, it should be easier to understand the browser API after learning the Ruby version. :-) I'm not sure why Opal's `Promise` implementation deviates from ES6 here, tbh.

If #9 ends up getting merged, Bowser will move completely to use `Bowser::Promise` (possibly even in the `ServiceWorker` branch if I can swing it).

**Comment by bwl21** [comment]
It seems that Opal's promise implementation deviates from ES6 since it provides the 'when'. So if Bowser::Promise is intended to replace Opal's Promise, it should at least be documented.

In my project, I have returned to Opals Promise and created an adapter to Dropbox v2 API.
